export const FETCH_FURNITURE_START = 'FETCH_FURNITURE_START';
export const FETCH_FURNITURE_SUCCESS = 'FETCH_FURNITURE_SUCCESS';
export const FETCH_FURNITURE_FAIL = 'FETCH_FURNITURE_FAIL';
export const FILTER_FURNITURE = 'FILTER_FURNITURE';
